name: Deploy Docc
on:
  # Runs on pushes where BrowserKit files are modified
  push:
    paths:
      - BrowserKit/Sources/ComponentLibrary/**
  workflow_dispatch: {} # adding the workflow_dispatch so it can be triggered manually

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      # Must be set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Build DocC
        run: |
          xcodebuild docbuild -project firefox-ios/Client.xcodeproj \
            -scheme ComponentLibrary \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          xcrun docc process-archive transform-for-static-hosting \
            /tmp/docbuild/Build/Products/Debug-iphoneos/ComponentLibrary.doccarchive \
            --hosting-base-path "firefox-ios" \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/componentlibrary\"</script>" > docs/index.html;
          echo "Building DocC step done"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
